include $(THEOS)/makefiles/common.mk
TWEAK_NAME = ICamControls
ICamControls_FILES = FloatingControls.m ../Core/ICPaths.m ../Core/ICSettings.m ../UI/ICAdjustments.m
ICamControls_CFLAGS = -fobjc-arc -I../Core -I../UI
ICamControls_FRAMEWORKS = UIKit Foundation
include $(THEOS_MAKE_PATH)/tweak.mk
